### PR TITLE
Upgraded to SnakeYAML 1.10

### PR DESCRIPTION
**Pull request by atrus6**

### CODE REVIEW

**Comment by ArneBab** [comment]
@infinity0 this looks useful, but currently it doesn’t merge. Can you take it up again so we can merge and release it?

**Comment by ArneBab** [comment]
@infinity0 could you have another look? (I am now in a position where I can release soon)

**Comment by infinity0** [comment]
Hey, I'm sorry but my attention is elsewhere these days and I won't be able to complete this. Feel free to take it over completely.

**Comment by desyncr** [comment]
@ArneBab Latest release is 1.26. Can be PR upgrade to the latest release? I'm up for it.

**Comment by ArneBab** [comment]
Sounds good.

**Comment by desyncr** [comment]
There's work already done at: https://github.com/redwerk/plugin-Library/tree/v37-dw-rw3

This PR should be closed.

**Comment by ArneBab** [comment]
Can you open another one for the new version?

**Comment by desyncr** [comment]
> Can you open another one for the new version?

Do you mean to implement the upgrade on another PR? Would not that cause a merge conflict the redwerk's work?

**Comment by ArneBab** [comment]
Closed in favor of https://github.com/freenet/plugin-Library/pull/15

**Pull request closed without merging**
